version: '3.8'
services:
  web:
    build: .
    command: python app.py
    volumes:
      - ./app:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres